appraisal/Models/ImportTs.cs
namespace appraisal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("d2014.ImportTs")]
    public partial class ImportTs
    {
        public ImportTs()
        {
            emp = new HashSet<emp>();
        }

            [Key]
            [Display(Name = "卡號")]
            [StringLength(5)]
            public string CardNo { get; set; }

            [Display(Name = "姓名")]
            [StringLength(45)]
            public string Name { get; set; }

            [Display(Name = "部門")]
            [StringLength(45)]
            public string Depart { get; set; }

            [Display(Name = "組別")]
            [StringLength(45)]
            public string Group { get; set; }

            [Display(Name = "管理職稱")]
            [StringLength(45)]
            public string MTitle { get; set; }

            [Display(Name = "專業職稱")]
            [StringLength(45)]
            public string PTitle { get; set; }

            [Display(Name = "個人")]
            [StringLength(45)]
            public string Personal { get; set; }

            [Display(Name = "今年曾任單位1")]
            [StringLength(45)]
            public string Job1 { get; set; }

            [Display(Name = "今年曾任單位2")]
            [StringLength(45)]
            public string Job2 { get; set; }

            [Display(Name = "考核等級")]
            [StringLength(4)]
            public string Type { get; set; }

            [Display(Name = "初評人員卡號")]
            [StringLength(45)]
            public string CardNo1 { get; set; }

            [Display(Name = "初評人員")]
            [StringLength(45)]
            public string Name1 { get; set; }

            [Display(Name = "複評人員卡號")]
            [StringLength(45)]
            public string CardNo2 { get; set; }

            [Display(Name = "複評人員")]
            [StringLength(45)]
            public string Name2 { get; set; }

            public virtual ICollection<emp> emp { get; set; }
    }
}

appraisal/Controllers/ImportTsController.cs
using System;
using System.IO;
using System.Net;
using appraisal.Models;
using appraisal.Infrastructure.Helpers;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using appraisal.Filters;
using PagedList;

namespace appraisal.Controllers
{
    [AuthorizeAD(Groups = "webAdmin01")]
    public class ImportTsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: ImportTs
        public ActionResult Index(int? page)
        {
            var query = db.importtss
                            .OrderBy(x => x.CardNo);

            var result = query.ToPagedList(pageNumber: page ?? 1, pageSize: 20);

            return View(result);
        }
        public ActionResult Details(string id, int? page)
        {
            if (id == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ImportTs its = db.importtss.Find(id);
            if (its == null)
            {
                return HttpNotFound();
            }
            ViewBag.CurrentPage = page;
            return View(its);
        }

        public ActionResult UpdateEmp(int? page)
        {
            ViewBag.CurrentPage = page;
            return View();
        }

        [HttpPost, ActionName("UpdateEmp")]
        public ActionResult UpdateEmpConfirmed(int? page)
        {
            string newTitle;
            string newGroup;
            int newDep = 0;
            var find = from data in db.importtss
                       where data.CardNo1 != null
                       select data;
            foreach (var item in find)
            {
                newTitle = String.IsNullOrEmpty(item.MTitle) ? item.PTitle : item.MTitle;
                newGroup = String.IsNullOrEmpty(item.Group) ? "" : item.Group;
                var deps = db.deps.Where(s => s.title.Contains(item.Depart.Trim()) && s.title.Contains(newGroup)).FirstOrDefault();
                if (deps != null)
                {
                        newDep = deps.id;
                }
                else
                { newDep = 0; }
                var empq = db.emps.Where(s => s.eid.ToUpper().Equals(item.CardNo.ToUpper())).FirstOrDefault();
                if (empq != null)
                {
                    empq.title = newTitle;
//                    emp1.dept = (newDep == 0) ? emp1.dept : newDep;
                    db.Entry(empq).State = EntityState.Modified;
                    db.SaveChanges();
                }
                else
                {
                    emp empa = new emp();
                    empa.eid = item.CardNo;
                    empa.cname = item.Name;
                    empa.title = newTitle;
                    empa.dept = (newDep == 0) ? 1 : newDep;                 
                    db.emps.Add(empa);
                    db.SaveChanges();
                }
            }

            return RedirectToAction("Index", new { page = page });
        }


        private string fileSavedPath = WebConfigurationManager.AppSettings["UploadPath"];

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            JObject jo = new JObject();
            string result = string.Empty;

            if (file == null)
            {
                jo.Add("Result", false);
                jo.Add("Msg", "請上傳檔案!");
                result = JsonConvert.SerializeObject(jo);
                return Content(result, "application/json");
            }
            if (file.ContentLength <= 0)
            {
                jo.Add("Result", false);
                jo.Add("Msg", "請上傳正確的檔案.");
                result = JsonConvert.SerializeObject(jo);
                return Content(result, "application/json");
            }

            string fileExtName = Path.GetExtension(file.FileName).ToLower();

            if (!fileExtName.Equals(".xls", StringComparison.OrdinalIgnoreCase)
                &&
                !fileExtName.Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
            {
                jo.Add("Result", false);
                jo.Add("Msg", "請上傳 .xls 或 .xlsx 格式的檔案");
                result = JsonConvert.SerializeObject(jo);
                return Content(result, "application/json");
            }

            try
            {
                var uploadResult = this.FileUploadHandler(file);

                jo.Add("Result", !string.IsNullOrWhiteSpace(uploadResult));
                jo.Add("Msg", !string.IsNullOrWhiteSpace(uploadResult) ? uploadResult : "");

                result = JsonConvert.SerializeObject(jo);
            }
            catch (Exception ex)
            {
                jo.Add("Result", false);
                jo.Add("Msg", ex.Message);
                result = JsonConvert.SerializeObject(jo);
            }
            return Content(result, "application/json");
        }

        /// <summary>
        /// Files the upload handler.
        /// </summary>
        /// <param name="file">The file.</param>
        /// <returns></returns>
        /// <exception cref="System.ArgumentNullException">file;上傳失敗：沒有檔案！</exception>
        /// <exception cref="System.InvalidOperationException">上傳失敗：檔案沒有內容！</exception>
        private string FileUploadHandler(HttpPostedFileBase file)
        {
            string result;

            if (file == null)
            {
                throw new ArgumentNullException("file", "上傳失敗：沒有檔案！");
            }
            if (file.ContentLength <= 0)
            {
                throw new InvalidOperationException("上傳失敗：檔案沒有內容！");
            }

            try
            {
                string virtualBaseFilePath = Url.Content(fileSavedPath);
                string filePath = HttpContext.Server.MapPath(virtualBaseFilePath);

                if (!Directory.Exists(filePath))
                {
                    Directory.CreateDirectory(filePath);
                }

                string newFileName = string.Concat(
                    DateTime.Now.ToString("yyyyMMddHHmmssfff"),
                    Path.GetExtension(file.FileName).ToLower());

                string fullFilePath = Path.Combine(Server.MapPath(fileSavedPath), newFileName);
                file.SaveAs(fullFilePath);

                result = newFileName;
            }
            catch (Exception ex)
            {
                throw;
            }
            return result;
        }

        [HttpPost]
        public ActionResult Import(string savedFileName)
        {
            var jo = new JObject();
            string result;

            try
            {
                var fileName = string.Concat(Server.MapPath(fileSavedPath), "/", savedFileName);

                var importts = new List<ImportTs>();

                var helper = new ImportDataHelper();
                var checkResult = helper.CheckImportData(fileName, importts);

                jo.Add("Result", checkResult.Success);
                jo.Add("Msg", checkResult.Success ? string.Empty : checkResult.ErrorMessage);

                if (checkResult.Success)
                {
                    //儲存匯入的資料
                    helper.SaveImportData(importts);
                }
                result = JsonConvert.SerializeObject(jo);
            }
            catch (Exception ex)
            {
                throw;
            }
            return Content(result, "application/json");
        }

    }
}

appraisal/Views/ImportTs/Details.cshtml
@model appraisal.Models.ImportTs
@{
    ViewBag.Title = "明細";
}

<h2>明細</h2>

<div>
    <h4>匯入考核資料</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CardNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Depart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Depart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Group)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Job1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Job2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CardNo1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardNo1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CardNo2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardNo2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name2)
        </dd>
    </dl>
</div>
<p>
       @Html.ActionLink("返回匯入評核資料", "Index", new { page = ViewBag.CurrentPage })
</p>

appraisal/Views/ImportTs/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<appraisal.Models.ImportTs>
@{
    ViewBag.Title = "匯入評核資料列表";
}

<h2>匯入評核資料列表</h2>

<div class="well">
    <button class="btn btn-primary" data-toggle="modal" data-target="#UploadModal">
        匯入資料
    </button>
    @Html.ActionLink("更新員工資料", "UpdateEmp", new { Page = Model.PageNumber })
</div>
@Html.PagedListPager(Model, page => Url.Action("Index", new { page })
                    , new PagedListRenderOptions { LinkToFirstPageFormat = "<<首頁", LinkToPreviousPageFormat = "<上一頁", LinkToNextPageFormat = "下一頁>", LinkToLastPageFormat = "末頁>>", MaximumPageNumbersToDisplay = 5 })

<table class="table table-striped table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().CardNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Depart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Group)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().MTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().PTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Name1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Name2)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CardNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Depart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PTitle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name2)
            </td>
            <td>
                @Html.ActionLink("明細", "Details", new { id = item.CardNo, Page = Model.PageNumber })
            </td>

        </tr>
    }

</table>

@Html.Partial("~/Views/Shared/_UploadFile.cshtml")

@section scripts
{
    <script src="~/Scripts/bootbox.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/project.js"></script>
    <script src="~/Scripts/project.extends.js"></script>
    <script src="~/Scripts/project.ZipCode.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var actionUrls = {
                Upload: '@Url.Action("Upload", "ImportTs")',
                Import: '@Url.Action("Import", "ImportTs")'
            };
            project.ZipCode.Initialize(actionUrls);
        });
    </script>
}

appraisal/Views/ImportTs/UpdateEmp.cshtml
@{
    ViewBag.Title = "更新員工資料";
}

<h2>更新員工資料</h2>

<h3>您想清楚了確定要更新員工資料嗎?</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="我很確定要更新員工資料" class="btn btn-default" /> |
        @Html.ActionLink("返回匯入考核資料", "Index", new { page = ViewBag.CurrentPage })
    </div>
}