appraisal/Controllers/otsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using appraisal.Models;
using appraisal.Filters;

namespace appraisal.Controllers
{
    //[Authorize(Users = @"administrator, K1336")]
    [AuthorizeAD(Groups = "webAdmin01,webHr01")]
    public class otsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ots    
        [LogActionFilter(ControllerName = "評核時間管理", ActionName = "瀏覽")]
        public ActionResult Index()
        {
            return View(db.ots.ToList().OrderBy(model => model.Vl));
        }

        // GET: ots/Details/5
        [LogActionFilter(ControllerName = "評核時間管理", ActionName = "明細")]
        public ActionResult Details(string sid)
        {
            if (sid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ots ots = db.ots.Find(sid);
            if (ots == null)
            {
                return HttpNotFound();
            }
            return View(ots);
        }

        // GET: ots/Create
        [LogActionFilter(ControllerName = "評核時間管理", ActionName = "新增")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ots/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [LogActionFilter(ControllerName = "評核時間管理", ActionName = "新增完成")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Skey,Vl")] ots ots)
        {
            if (ModelState.IsValid)
            {
                db.ots.Add(ots);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ots);
        }

        // GET: ots/Edit/5
        [LogActionFilter(ControllerName = "評核時間管理", ActionName = "編輯")]
        public ActionResult Edit(string sid)
        {
            if (sid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ots ots = db.ots.Find(sid);
            if (ots == null)
            {
                return HttpNotFound();
            }
            return View(ots);
        }

        // POST: ots/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
         [LogActionFilter(ControllerName = "評核時間管理", ActionName = "編輯完成")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Skey,Vl")] ots ots)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ots).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ots);
        }

        // GET: ots/Delete/5
        [LogActionFilter(ControllerName = "評核時間管理", ActionName = "刪除")]
        public ActionResult Delete(string sid)
        {
            if (sid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ots ots = db.ots.Find(sid);
            if (ots == null)
            {
                return HttpNotFound();
            }
            return View(ots);
        }

        // POST: ots/Delete/5
        [LogActionFilter(ControllerName = "評核時間管理", ActionName = "刪除完成")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string sid)
        {
            ots ots = db.ots.Find(sid);
            db.ots.Remove(ots);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

appraisal/Controllers/tsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using appraisal.Models;
using appraisal.Filters;
using appraisal.Infrastructure.CustomResults;
using PagedList;

namespace appraisal.Controllers
{
    public class tsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();       
        // GET: ts
        [AuthorizeAD(Groups = "webAdmin01,webHr01")]
        [LogActionFilter(ControllerName = "考核紀錄管理", ActionName = "瀏覽")]
        public ActionResult Index(int? page, int? itemsPerPage, string sortOrder, string searchString)
        {
            ViewBag.CurrentItemsPerPage = itemsPerPage;
            ViewBag.IDSortParm = String.IsNullOrEmpty(sortOrder) ? "ID_Desc" : "";
            ViewBag.NameSortParm = sortOrder == "Name" ? "Name_Desc" : "Name"; 
            ViewBag.DeptSortParm = sortOrder == "Dept" ? "Dept_Desc" : "Dept";
            ViewBag.SubjSortParm = sortOrder == "Subj" ? "Subj_Desc" : "Subj";
            ViewBag.MangSortParm = sortOrder == "Mang" ? "Mang_Desc" : "Mang";
            ViewBag.VLSortParm = sortOrder == "VL" ? "VL_Desc" : "VL";
            ViewBag.OldSortParm = sortOrder;
            if (searchString == "*")
            { searchString = ""; }
            ViewBag.CurrentFilter = searchString;
            var emp = db.ts.OrderBy(x => x.id); ;
            var items = from item in emp select item;
            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(s => s.emp1.cname.ToUpper().Contains(searchString.ToUpper())
                                        || s.emp1.eid.ToUpper().Contains(searchString.ToUpper())
                                        || s.emp1.dep.title.ToUpper().Contains(searchString.ToUpper())
                                        || s.exm1.subject.ToUpper().Contains(searchString.ToUpper())
                                        || s.emp2.cname.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "ID_Desc":
                    items = items.OrderBy(x => x.emp1.eid);
                    break;
                case "Name":
                    items = items.OrderBy(x => x.emp1.cname);
                    break;
                case "Name_Desc":
                    items = items.OrderByDescending(x => x.emp1.cname);
                    break;
                case "Dept":
                    items = items.OrderBy(x => x.emp1.dep.title);
                    break;
                case "Dept_Desc":
                    items = items.OrderByDescending(x => x.emp1.dep.title);
                    break;
                case "Subj":
                    items = items.OrderBy(x => x.exm1.subject);
                    break;
                case "Subj_Desc":
                    items = items.OrderByDescending(x => x.exm1.subject);
                    break;
                case "Mang":
                    items = items.OrderBy(x => x.emp2.cname);
                    break;
                case "Mang_Desc":
                    items = items.OrderByDescending(x => x.emp2.cname);
                    break;
                case "VL":
                    items = items.OrderBy(x => x.vl);
                    break;
                case "VL_Desc":
                    items = items.OrderByDescending(x => x.vl);
                    break;
                default:
                    items = items.OrderByDescending(x => x.emp1.eid);
                    break;
            }
            return View(items.ToPagedList(pageNumber: page ?? 1, pageSize: itemsPerPage ?? 10));
        }

        // GET: ts/Details/5
        [AuthorizeAD(Groups = "webAdmin01,webHr01")]
        [LogActionFilter(ControllerName = "考核紀錄管理", ActionName = "明細")]
        public ActionResult Details(int? id, int? page, int? itemsPerPage, string sortOrder, string searchString)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ts ts = db.ts.Find(id);
            if (ts == null)
            {
                return HttpNotFound();
            }
            ViewBag.CurrentPage = page;
            ViewBag.CurrentItemsPerPage = itemsPerPage;
            ViewBag.OldSortParm = sortOrder;
            ViewBag.CurrentFilter = searchString;
            return View(ts);
        }

        // GET: ts/Create
        [AuthorizeAD(Groups = "webAdmin01")]
        [LogActionFilter(ControllerName = "考核紀錄管理", ActionName = "新增")]
        public ActionResult Create(int? page, int? itemsPerPage, string sortOrder, string searchString)
        {
            ViewBag.DropDownList1 = new SelectList(db.exms, "id", "subject");
            List<emp> reasonList = db.emps.OrderBy(m => m.cname).ToList();
            ViewBag.DropDownList2 = new SelectList(reasonList, "id", "cname");
            ViewBag.CurrentPage = page;
            ViewBag.CurrentItemsPerPage = itemsPerPage;
            ViewBag.OldSortParm = sortOrder;
            ViewBag.CurrentFilter = searchString;
            return View();
        }

        // POST: ts/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [AuthorizeAD(Groups = "webAdmin01")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [LogActionFilter(ControllerName = "考核紀錄管理", ActionName = "新增完成")]
        public ActionResult Create([Bind(Include = "id,emp,exm,boss,vl,suggest,lockAudit")] ts ts, int? page, int? itemsPerPage, string sortOrder, string searchString)
        {
            ViewBag.DropDownList1 = new SelectList(db.exms, "id", "subject");
            List<emp> reasonList = db.emps.OrderBy(m => m.cname).ToList();
            ViewBag.DropDownList2 = new SelectList(reasonList, "id", "cname");
            if (ModelState.IsValid)
            {
                db.ts.Add(ts);
                db.SaveChanges();
                return RedirectToAction("Index", new { page = page, itemsPerPage = itemsPerPage, sortOrder = sortOrder, searchString = searchString });
            }

            return View(ts);
        }

        // GET: ts/Edit/5
        [AuthorizeAD(Groups = "webAdmin01")]
        [LogActionFilter(ControllerName = "考核紀錄管理", ActionName = "編輯")]
        public ActionResult Edit(int? id, int? page, int? itemsPerPage, string sortOrder, string searchString)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ts ts = db.ts.Find(id);
            if (ts == null)
            {
                return HttpNotFound();
            }
            var empl = db.emps.OrderBy(m => m.cname).ToList();
            SelectList selectList1 = new SelectList(empl, "id", "cname", ts.emp);
            SelectList selectList2 = new SelectList(empl, "id", "cname", ts.boss);
            var exml = db.exms.ToList();
            SelectList selectList3 = new SelectList(exml, "id", "subject", ts.exm);
            int ipp = itemsPerPage == null ? 10 : (int)itemsPerPage;
            tsEditViewModels viewModel = new tsEditViewModels()
            {
                tsa = ts,
                empList = selectList1,
                bossList = selectList2,
                exmList = selectList3,
                pageno = (int)page,
                v_itemsPerPage = ipp,
                v_currentFilter = searchString,
                v_sortOrder = sortOrder
            };
            return View(viewModel);
        }

        // POST: ts/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [AuthorizeAD(Groups = "webAdmin01")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [LogActionFilter(ControllerName = "考核紀錄管理", ActionName = "編輯完成")]
        public ActionResult Edit([Bind(Include = "tsa,pageno,v_itemsPerPage,v_currentFilter,v_sortOrder")] tsEditViewModels tsv)
        {
            if (ModelState.IsValid)
            {
                var tsb = tsv.tsa;
                db.Entry(tsb).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { page = tsv.pageno, itemsPerPage = tsv.v_itemsPerPage, sortOrder = tsv.v_sortOrder, searchString = tsv.v_currentFilter });
            }
            return View(tsv);
        }

        // GET: ts/Delete/5
        [AuthorizeAD(Groups = "webAdmin01")]
        [LogActionFilter(ControllerName = "考核紀錄管理", ActionName = "刪除")]
        public ActionResult Delete(int? id, int? page, int? itemsPerPage, string sortOrder, string searchString)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.CurrentPage = page;
            ViewBag.CurrentItemsPerPage = itemsPerPage;
            ViewBag.CurrentFilter = searchString;
            ViewBag.OldSortParm = sortOrder;
            ts ts = db.ts.Find(id);
            if (ts == null)
            {
                return HttpNotFound();
            }
            return View(ts);
        }

        // POST: ts/Delete/5
        [AuthorizeAD(Groups = "webAdmin01")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [LogActionFilter(ControllerName = "考核紀錄管理", ActionName = "刪除完成")]
        public ActionResult DeleteConfirmed(int id, int? page, int? itemsPerPage, string sortOrder, string searchString)
        {
            ts ts = db.ts.Find(id);
            db.ts.Remove(ts);
            db.SaveChanges();
            return RedirectToAction("Index", new { page = page, itemsPerPage = itemsPerPage, sortOrder = sortOrder, searchString = searchString });
        }

appraisal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 2014@國光</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @using Microsoft.AspNet.Identity
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      @Scripts.Render("~/bundles/oldIEBrowsersSupport")
    <![endif]-->

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("2014年績效考核", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--<li>@Html.ActionLink("首頁", "Index", "Home")</li>-->
                    <li>@Html.ActionLink("說明", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡方式", "Contact", "Home")</li>
                    <!--<li>@Html.ActionLink("測試", "KP", "Home")</li>-->
                </ul>                             
                @Html.Partial("_LoginPartial")
                @if (Request.IsAuthenticated)
                {
                    if (Session["UserGroup"].ToString().Contains("webAdmin01;") | Session["UserGroup"].ToString().Contains("webHr01;"))
                    {
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color:red">後台管理<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Index", "ots")"><i class="icon-off"></i>評核時間</a></li>
                                    <li><a href="@Url.Action("Index", "ts")"><i class="icon-off"></i>評核紀錄</a></li>
                                    @if (Session["UserGroup"].ToString().Contains("webAdmin01;"))
                                    {
                                        <li><a href="@Url.Action("Index", "ImportTs")"><i class="icon-off"></i>匯入評核資料</a></li>
                                        <li><a href="@Url.Action("Index", "emps")"><i class="icon-off"></i>員工</a></li>
                                        <li><a href="@Url.Action("Index", "deps")"><i class="icon-off"></i>部門</a></li>
                                        <li><a href="@Url.Action("Index", "exms")"><i class="icon-off"></i>評核類別</a></li>
                                        <li><a href="@Url.Action("Index", "actlogs")"><i class="icon-off"></i>Logs</a></li>
                                    }
                                </ul>
                            </li>
                        </ul>
                    }
                } 
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 國光生技績效考核</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

appraisal/Views/Shared/_UploadFile.cshtml
<!-- UploadModal -->
<div class="modal fade" id="UploadModal" tabindex="-1" role="dialog" aria-labelledby="UploadModalLabel" aria-hidden="true">
    <form id="UploadForm" action="@Url.Action("Upload", "ImportTs")" method="post" enctype="multipart/form-data">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="UploadModalLabel">上傳並匯入資料</h4>
                </div>
                <div class="modal-body">

                    <div class="fileinput fileinput-new input-group" data-provides="fileinput">
                        <div class="form-control" data-trigger="fileinput">
                            <i class="glyphicon glyphicon-file fileinput-exists"></i>
                            <span class="fileinput-filename"></span>
                        </div>
                        <span class="input-group-addon btn btn-default btn-file">
                            <span class="fileinput-new">選擇檔案</span>
                            <span class="fileinput-exists">更換檔案</span>
                            <input type="file" name="file" id="file" />
                        </span>
                        <a href="#" class="input-group-addon btn btn-default fileinput-exists" data-dismiss="fileinput">移除檔案</a>
                    </div>


                </div>
                <div class="modal-footer">
                    <input type="button" id="ButtonCancel" class="btn btn-default" data-dismiss="modal" value="取消">
                    <input type="submit" id="ButtonSubmit" name="ButtonSubmit" class="btn btn-primary" value="上傳檔案">
                </div>
            </div>
        </div>
    </form>
</div>